services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - fiapx-videos

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    networks:
      - fiapx-videos

networks:
  fiapx-videos:
    driver: bridge